/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'customerName' : string,
  'address' : string,
  'timestamp' : bigint,
  'mobile' : string,
  'products' : Array<Product>,
}
export interface Product {
  'id' : bigint,
  'title' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface _SERVICE {
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getOrderById' : ActorMethod<[bigint], Order>,
  'submitOrder' : ActorMethod<
    [string, string, string, Array<Product>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];