/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : IDL.Int,
  'mobile' : IDL.Text,
  'products' : IDL.Vec(Product),
});

export const idlService = IDL.Service({
  'deleteOrder' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
  'submitOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Product)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : IDL.Int,
    'mobile' : IDL.Text,
    'products' : IDL.Vec(Product),
  });
  
  return IDL.Service({
    'deleteOrder' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
    'submitOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Product)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };